# Generated by Django 2.0.2 on 2018-04-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_round_concert_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='concert_id',
        ),
    ]
