# Generated by Django 2.0.2 on 2018-04-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20180429_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='concert_id',
        ),
    ]
