# Generated by Django 2.0.2 on 2018-04-30 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_ticket_concert_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='concert_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.Concert'),
        ),
    ]
