# Generated by Django 2.0.2 on 2018-04-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_round_concert_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='concert_id',
            new_name='concert',
        ),
    ]
