# Generated by Django 2.0.2 on 2018-04-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20180430_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='concert',
            new_name='concert_id',
        ),
    ]
