# Generated by Django 2.0.2 on 2018-04-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20180430_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='concert_id',
            new_name='concert',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='round_id',
            new_name='round',
        ),
    ]
