# Generated by Django 2.0.1 on 2018-05-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20180430_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='numbero',
            new_name='no',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='round',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='concert',
        ),
        migrations.AddField(
            model_name='ticket',
            name='concert',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.Concert'),
        ),
        migrations.AddField(
            model_name='zone',
            name='Round',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.Round'),
        ),
    ]
