# Generated by Django 2.0.1 on 2018-05-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20180502_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='stop',
        ),
    ]
