# Generated by Django 2.0.1 on 2018-05-02 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_round_stop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='Round',
            new_name='round',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='concert',
        ),
        migrations.AddField(
            model_name='ticket',
            name='zone',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.Zone'),
        ),
    ]
