# Generated by Django 2.0.1 on 2018-05-05 18:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20180502_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment', models.CharField(default='Registration', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer')),
                ('ticket', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.Ticket')),
            ],
        ),
    ]
