# Generated by Django 2.0.2 on 2018-05-06 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment', models.CharField(default='Registration', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=300)),
                ('slip', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('buyer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.Customer')),
                ('ticket', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.Ticket')),
            ],
        ),
        migrations.RemoveField(
            model_name='buy',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
