# Generated by Django 2.0.2 on 2018-05-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20180509_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
