# Generated by Django 2.0.2 on 2018-05-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20180509_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
