# Generated by Django 2.0.2 on 2018-05-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_auto_20180509_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_name',
        ),
    ]
