# Generated by Django 2.0.4 on 2018-05-13 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_auto_20180510_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='images/usersymbol.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
