# Generated by Django 2.0.4 on 2018-05-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_auto_20180513_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='images/usersymbol.png', null=True, upload_to='images/'),
        ),
    ]
